repos:
  - repo: local
    hooks:
      - id: uv-pip-compile
        name: Compile requirements.txt
        entry: uv pip compile pyproject.toml -o requirements.txt --no-header --no-annotate --no-deps
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace  # Remove espaços em branco no final das linhas
        name: Trim trailing whitespace
      - id: end-of-file-fixer  # Garante uma linha vazia no final do arquivo
        name: Fix end of files
