[project]
name = "cleanarchitecture"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "mysql-connector-python==9.2.0",
    "pymysql==1.1.1",
    "pytest==8.3.5",
    "sqlalchemy==2.0.40",
]

[dependency-groups]
dev = [
    "pre-commit==4.2.0",
    "ruff==0.11.2",
]
